### ISSUE TITLE
 Unresolved assembly reference: Newtonsoft.Json (Newtonsoft.Json, Version=6.0.0.0...

### ISSUE THREAD

**Issue by Mrunali31** [EWSoftware/SHFB#388]
Getting below error while building and not able to find Newtonsoft.Json, Version=6.0.0.0 in nuget package manager or online dll to manually add.. Pls help.

MRefBuilder : error : Unresolved assembly reference: Newtonsoft.Json (Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed) required by System.Web.Http [D:\Help\Working\GenerateRefInfo.proj]
    Last step completed in 00:00:03.3943
-------------------------------

SHFB: Error BE0043: Unexpected error detected in last build step.  See output above for details.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.RunProcess(String fileToRun, String args)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

**Comment by EWSoftware** [comment]
Assuming you are talking about building a documentation project, you should find the assembly as part of the assembly's project that's being documented.  If you use the solution or project as the documentation source, it should resolve the reference automatically.  If you are using the assembly as the documentation source directly, you'll need to find the Newtonsoft.Json assembly and add it as a reference in the SHFB project's References node.

Assuming you can build the assembly being documented, you should look in its project folder for the assembly either in the bin\ folder or the packages\ folder if its coming from NuGet.  If you have a newer or older version of the assembly, you can use the Assembly Binding Redirect plug-in to redirect the older/new reference to the one you've got.

**Comment by Mrunali31** [comment]
Yes, i am talking about building a documentation project.
In my project(for which i am trying to build documnetation) , i am using Newtonsoft.Json, Version=9.0.1 by adding it using Manage Nuget Packackes. 
Not sure why while building documentation SHFB is asking for Newtonsoft.Json, Version=6.0.0.0..

My project uses .Net Framwork 4.6.1.  Please help.

**Comment by EWSoftware** [comment]
One of the other assemblies in the project is probably using an older version.  As noted, use the [Assembly Binding Redirection plug-in](http://ewsoftware.github.io/SHFB/html/f5051d32-b973-4fe1-9ffe-e30531007691.htm) to redirect the old reference to the new one.

**Comment by Mrunali31** [comment]
I could find the file for plug in at [(https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderPlugIns/BindingRedirectResolverPlugIn.cs)]((https://github.com/EWSoftware/SHFB/blob/master/SHFB/Source/SandcastleBuilderPlugIns/BindingRedirectResolverPlugIn.cs))

However, couldn't find any documentation of where to download this plug in from and how and where to install it.. pls guide.

**Comment by Mrunali31** [comment]
Thanks for the solution. I tried it but still getting below error.

  Creating directory "obj\Debug\".
GenerateRefInfo:
  MRefBuilder (v2015.1.12.0)
  Copyright c 2006-2015, Microsoft Corporation, All Rights Reserved.
  Portions Copyright c 2006-2014, Eric Woodruff, All Rights Reserved.
  Loaded assembly binding redirect: Newtonsoft.Json, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, Version(s) 6.0.0.0 redirect to Version 9.0.1.0
  Loaded 1 assemblies for reflection and 2 dependency assemblies.
MRefBuilder : error : Unresolved assembly reference: Newtonsoft.Json (Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed) required by System.Web.Http [D:\Help\Working\GenerateRefInfo.proj]
    Last step completed in 00:00:08.5439
-------------------------------

SHFB: Error BE0043: Unexpected error detected in last build step.  See output above for details.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.RunProcess(String fileToRun, String args)
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

![image](https://cloud.githubusercontent.com/assets/25223529/22171817/d428d27e-dfbc-11e6-96b6-e40ecf007775.png)
 I even tried Ignore if unresolved. see screenshot below..but still getting same error.

![image](https://cloud.githubusercontent.com/assets/25223529/22171829/266a3de8-dfbd-11e6-9799-48d8aa35f199.png)

**Comment by EWSoftware** [comment]
If you want to ignore it, just enter the base name (Newtonsoft.Json).  Leave off the version, culture, and public key token.
