### ISSUE TITLE
 SHFB : error BHT0002: Unable to build project 'PROJECT_NAME': SandcastleBuilder.Utils.BuilderException: Error reading project from 

### ISSUE THREAD

**Issue by ciaranduncan14596** [EWSoftware/SHFB#401]
Hi, 

Has stopped building recently with the following error message shown above?

Cheers,
Ciaran

**Comment by EWSoftware** [comment]
Are there any other warnings prior to the error?  Are you using the latest release of SHFB? Are you using an appropriate version of MSBuild (12.0 or later)?

**Comment by ciaranduncan14596** [comment]
the first sign of failure i get is: 
Done Building Project "" (default targets) -- FAILED.

**Comment by ciaranduncan14596** [comment]
In terms of error messaging i can give you:

PROJECT
Done Building Project "PROJECT.csproj.metaproj" (default targets).
Project "PROJECT.sln" (1) is building "PROJECT.shfbproj.metaproj" (5) on node 1 (default targets).
Project "PROJECT.shfbproj.metaproj" (5) is building "PROJECT.shfbproj" (6) on node 1 (default targets).
PreBuildEvent:
  echo Adding Docs.chm to: CPROJECT\bin\Release\%ProductNameèmo_%MajorVersion%_%MinorVersion%_%IncrementalVersion%_%Revision%.zip
  Adding Docs.chm to: CPROJECT\bin\Release\MajorVersionMinorVersionIncrementalVersionRevision.zip
SHFB : error BHT0002: Unable to build project 'PROJECT.shfbproj': SandcastleBuilder.Utils.BuilderException: Error reading project from 'PROJECT.shfbproj': [PROJECT.shfbproj]
SHFB : error BHT0002: An attempt was made to set a read-only or ignored property: Microsoft.Build.Evaluation.ProjectProperty+ProjectPropertyNotXmlBacked   Value: PROJECT_3_3_3_7309.zip ---> SandcastleBuilder.Utils.BuilderException: An attempt was made to set a read-only or ignored property: Microsoft.Build.Evaluation.ProjectProperty+ProjectPropertyNotXmlBacked   Value: PROJECT_3_3_3_7309.zip [PROJECT.shfbproj]
SHFB : error BHT0002:    at SandcastleBuilder.Utils.SandcastleProject.SetLocalProperty(ProjectProperty msBuildProperty, String value) [PROJECT.shfbproj]
SHFB : error BHT0002:    at SandcastleBuilder.Utils.SandcastleProject.LoadProperties() [PROJECT.shfbproj]
SHFB : error BHT0002:    --- End of inner exception stack trace --- [PROJECT.shfbproj]
SHFB : error BHT0002:    at SandcastleBuilder.Utils.SandcastleProject.LoadProperties() [PROJECT.shfbproj]
SHFB : error BHT0002:    at SandcastleBuilder.Utils.SandcastleProject..ctor(Project existingProject) [PROJECT.shfbproj]
SHFB : error BHT0002:    at SandcastleBuilder.Utils.MSBuild.BuildHelp.Execute() [PROJECT.shfbproj]
Done Building Project "PROJECT.shfbproj" (default targets) -- FAILED.
Done Building Project "PROJECT.shfbproj.metaproj" (default targets) -- FAILED.
Done Building Project "PROJECT.sln" (PROJECTtarget(s)) -- FAILED.

This is being used with Jenkins. I feel like its using the wrong revision number or something similar?

**Comment by EWSoftware** [comment]
> An attempt was made to set a read-only or ignored property:

That is most likely the actual cause of the failure.  Make sure you are using SHFB v2016.9.17.0 or later as that issue was fixed.  If you are, then your build really is trying to set a read-only/ignore SHFB project property.  Whatever it is, it has the value "PROJECT_3_3_3_7309.zip".  You'll need to remove that property from the SHFB project or change its name so that it doesn't conflict with the internal SHFB property.

**Comment by ciaranduncan14596** [comment]
Hi, 

Thanks for the quick response again, how do i check the version number of SHFB, would upgrading this fix my problem if not would it be a fix in the pre-vuild event or the post build event?

**Comment by EWSoftware** [comment]
The version is listed at the start of the SHFB build log, if you have one, if you open it in a text editor.  You can also use the About box in the standalone GUI.  You can also get it from the file properties on any of the SHFB executables.

As noted in my prior response if upgrading does not fix it, then your build really is trying to set a read-only/ignored SHFB project property. Whatever it is, it has the value "PROJECT_3_3_3_7309.zip". You'll need to remove that property from the SHFB project or change its name so that it doesn't conflict with the internal SHFB property.

**Comment by ciaranduncan14596** [comment]
It looks like the PROJECT_3_3_3_7309.zip doesnt exist anywhere, and i cant figure out how its attempting to build it? is there a way of finding this out?

**Comment by ciaranduncan14596** [comment]
My Project is set up to build PROJECT_3_3_3_7355.zip but its looking for the 7309

**Comment by EWSoftware** [comment]
You've got a project property or an environment variable set to that value.  The name of the property/variable matches something in the SHFB project file.  Try building from the command line with MSBuild.  If it works there, then it's something in your Jenkins build that's not working.  That I can't help you with since I know nothing about it.
