### ISSUE TITLE
Plug-Ins will not load (System.Runtime.Serialization version 5.0.5 not found)

### ISSUE THREAD

**Issue by sestho** [EWSoftware/SHFB#439]
My project suddenly stopped building. This is the error popup I get when opening the project.

![image](https://cloud.githubusercontent.com/assets/26625633/24247841/a6beaf98-0fcd-11e7-8c19-e32e695a67ab.png)

This error shows even when I just open the Sandcastle Help File Builder without a project!

And the message on the build server is

SHFB error BE0065: BUILD FAILED: Could not load file or assembly 'System.Runtime.Serialization, Version=5.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. The system cannot find the file specified.

[06:19:07][SandcastleBuilder.Utils.MSBuild.BuildHelp] Failed

/Stefan

**Comment by EWSoftware** [comment]
Do you perhaps have a custom build component installed that is missing something?  It would be in the folder specified by the project's Component Path property if set, an assembly somewhere in the folder or sub-folders where the project is stored, or in one the [shared component location](http://ewsoftware.github.io/SHFB/html/a24489fb-45d6-46f4-9eaa-9a9c4e0919b2.htm#BuildComponents).

If your SHFB project is in the same location as the projects being documented, it may be searching the project outputs for build components.  Moving the SHFB project to a sub-folder or a different location so that it only searches its own folder and sub-folders should solve the issue if that's the case.

**Comment by sestho** [comment]
Thanks for a prompt reply.

This implies that whenever you just start the program without a project it will remember the path of the last project you opened, right?

I will get back with my findings.

**Comment by EWSoftware** [comment]
Yes, the standalone GUI does load the most recently used project at startup.  It also remembers the last selected project category in the properties window.  The error you're getting is from either the Components or Plug-Ins category.  If another category is selected and you restart, you probably won't see the error until you select either of those tabs or do a build.

**Comment by sestho** [comment]
It worked like a charm after moving the SHFB projects to a subfolder and changing all the relative paths.
I still can't figure out what the program is trying to do before you open a project file.

**Comment by EWSoftware** [comment]
It searches for build components and plug-ins.  If the project is in the same location or in a folder above those containing the documented assemblies, it will try to load them to search for components as well as any other assemblies it finds.  Moving it to a subfolder prevents that from happening.

**Comment by sestho** [comment]
I suggest that the program should not do anything before you open a project or create a new one.
